### ISSUE TITLE
ICMP monitor not working

### ISSUE THREAD

**Issue by berndonline** [AlekseyChudov/powergslb#1]
Hello,
Great GSLB addon for PowerDNS, really like it, good job.

The ICMP monitor is not working correctly, it show status "on" even when the IP address is not reachable.
The other monitor checks like HTTP via ports 80 or 443 works perfectly.

Regards,
Bernd

**Comment by acudovs** [comment]
Hi Bernd,

I have checked ICMP monitor by enabling it for "example.com 192.0.2.101 A" record and it works for me in CentOS 7.3.1611 Docker container and KVM machine. Please report your PowerGSLB version, OS distribution and Python version for details. Please also check systemd logs (journalctl or /var/log/messages) for investigation. You should see something like the following or some error messages

```
Mar 05 18:06:01 0622a5ef8e68 powergslb[863]: DEBUG: MonitorThread: checks updated: [{'content': u'192.0.2.101', 'id': 67, 'monitor_json': {'rise': 5, 'timeout': 1, 'fall': 3, 'ip': '192.0.2.101', 'interval': 3, 'type': 'icmp'}}]
Mar 05 18:06:02 0622a5ef8e68 powergslb[863]: DEBUG: Check-67: {'rise': 5, 'timeout': 1, 'fall': 3, 'ip': '192.0.2.101', 'interval': 3, 'type': 'icmp'}: return False
Mar 05 18:06:06 0622a5ef8e68 powergslb[863]: DEBUG: Check-67: {'rise': 5, 'timeout': 1, 'fall': 3, 'ip': '192.0.2.101', 'interval': 3, 'type': 'icmp'}: return False
Mar 05 18:06:10 0622a5ef8e68 powergslb[863]: DEBUG: Check-67: {'rise': 5, 'timeout': 1, 'fall': 3, 'ip': '192.0.2.101', 'interval': 3, 'type': 'icmp'}: return False
Mar 05 18:06:10 0622a5ef8e68 powergslb[863]: ERROR: Check-67: {'rise': 5, 'timeout': 1, 'fall': 3, 'ip': '192.0.2.101', 'interval': 3, 'type': 'icmp'}: status fall
```

Regards,
Aleksey

**Comment by acudovs** [comment]
Please reopen this issue if the problem persists.
