### ISSUE TITLE
powergslb 1.7.1 is not working with pdns-4.1.10

### ISSUE THREAD

**Issue by orchowei** [AlekseyChudov/powergslb#13]
I installed powergslb 1.7.1 as your guide for 'Installation on CentOS 7', but, it did not work.
I tried to find the problem and eventually found that the pdns version was the problem.

in /var/log/messages/
pdns-4.1.10 
-------------------------------
Jul 15 17:22:57 **** powergslb: DEBUG: Thread-1: MySQLDatabase: "SELECT `names`.`name` AS `qname`, `types`.`type` AS `qtype`, `names_types`.`ttl`, `names_types`.`persistence`, `records`.`fallback`, `records`.`weight`, `contents_monitors`.`id`, `contents`.`content`, `views`.`rule` FROM `names` JOIN `names_types` ON `names`.`id` = `names_types`.`name_id` JOIN `types` ON `names_types`.`type_value` = `types`.`value` JOIN `records` ON `names_types`.`id` = `records`.`name_type_id` JOIN `contents_monitors` ON `records`.`content_monitor_id` = `contents_monitors`.`id` JOIN `contents` ON `contents_monitors`.`content_id` = `contents`.`id` JOIN `views` ON `records`.`view_id` = `views`.`id` WHERE `names`.`name` = %s AND `types`.`type` = %s AND `records`.`disabled` = 0" % ('example%2ecom%2e', 'SOA')
---------------------------------
pdns-4.1.6
---------------------------------
Jul 15 17:33:10 **** powergslb: DEBUG: Thread-2: MySQLDatabase: "SELECT `names`.`name` AS `qname`, `types`.`type` AS `qtype`, `names_types`.`ttl`, `names_types`.`persistence`, `records`.`fallback`, `records`.`weight`, `contents_monitors`.`id`, `contents`.`content`, `views`.`rule` FROM `names` JOIN `names_types` ON `names`.`id` = `names_types`.`name_id` JOIN `types` ON `names_types`.`type_value` = `types`.`value` JOIN `records` ON `names_types`.`id` = `records`.`name_type_id` JOIN `contents_monitors` ON `records`.`content_monitor_id` = `contents_monitors`.`id` JOIN `contents` ON `contents_monitors`.`content_id` = `contents`.`id` JOIN `views` ON `records`.`view_id` = `views`.`id` WHERE `names`.`name` = %s AND `types`.`type` = %s AND `records`.`disabled` = 0" % ('example.com', 'SOA')
--------------------------------

I think  that 'example%2ecom%2e' is the problem.

How can i solve this problem?

Thanks

**Comment by binsil** [comment]
I am also facing similar issue after powergslb installation on centos 7. When I dig example.com from the server I get the following error.
````
Jul 18 13:39:55 powergslb: DEBUG: Thread-1: MySQLDatabase: 0 rows returned
Jul 18 13:39:55 powergslb: 127.0.0.1 - - [18/Jul/2019 13:39:55] "GET /dns/lookup/%2e/SOA HTTP/1.1" 200 -
Jul 18 13:39:55  powergslb: DEBUG: Thread-1: HTTPRequestHandler: {"result":[]}
````

**Comment by acudovs** [comment]
Thanks for reporting the problem! You can try [PowerGSLB Docker image](https://github.com/AlekseyChudov/powergslb#using-powergslb-docker-image) until I fix it.

**Comment by binsil** [comment]
Hi,

Is there any previous working version ### available? I have also tried 1.6.6 and the result is the same!!

**Comment by acudovs** [comment]
It seems to me that https://github.com/PowerDNS/pdns/pull/7577 breaks compatibility. Try pdns 4.1.6 as workaround until I fix it.

**Comment by acudovs** [comment]
Fixed in 1f1b6d9. Please try powergslb 1.7.2.

**Comment by orchowei** [comment]
Thanks. AlekseyChudov

**Comment by binsil** [comment]
Thanks, it is working fine now.
