### ISSUE TITLE
Not able to dig new domain 

### ISSUE THREAD

**Issue by binsil** [AlekseyChudov/powergslb#14]
Hi,

I have installed the new version and now the template domains are responding to the DNS queries. I have added a new domain to the server from the panel. After, adding the new domain and a new A record, I was not able to dig the newly added domain. I was getting the following error. 
```````
Aug  1 12:51:01 ip-172-31-38-17 powergslb: DEBUG: Thread-2: MySQLDatabase: 0 rows returned
Aug  1 12:51:01 ip-172-31-38-17 powergslb: 127.0.0.1 - - [01/Aug/2019 12:51:01] "GET /dns/lookup/nl%2e/SOA HTTP/1.1" 200 -
Aug  1 12:51:01 ip-172-31-38-17 powergslb: DEBUG: Thread-2: HTTPRequestHandler: {"result":[]}
Aug  1 12:51:01 ip-172-31-38-17 powergslb: DEBUG: Thread-2: MySQLDatabase: "SELECT `names`.`name` AS `qname`, `types`.`type` AS `qtype`, `names_types`.`ttl`, `names_types`.`persistence`, `records`.`fallback`, `records`.`weight`, `contents_monitors`.`id`, `contents`.`content`, `views`.`rule` FROM `names` JOIN `names_types` ON `names`.`id` = `names_types`.`name_id` JOIN `types` ON `names_types`.`type_value` = `types`.`value` JOIN `records` ON `names_types`.`id` = `records`.`name_type_id` JOIN `contents_monitors` ON `records`.`content_monitor_id` = `contents_monitors`.`id` JOIN `contents` ON `contents_monitors`.`content_id` = `contents`.`id` JOIN `views` ON `records`.`view_id` = `views`.`id` WHERE `names`.`name` = %s AND `types`.`type` = %s AND `records`.`disabled` = 0" % ('', 'SOA')
Aug  1 12:51:01 ip-172-31-38-17 powergslb: DEBUG: Thread-2: MySQLDatabase: 0 rows returned
Aug  1 12:51:01 ip-172-31-38-17 powergslb: 127.0.0.1 - - [01/Aug/2019 12:51:01] "GET /dns/lookup/%2e/SOA HTTP/1.1" 200 -
Aug  1 12:51:01 ip-172-31-38-17 powergslb: DEBUG: Thread-2: HTTPRequestHandler: {"result":[]}
```````
Can you check on this.

**Comment by binsil** [comment]
Hi,

Any update on this ?

**Comment by acudovs** [comment]
Hi,

I can not reproduce the problem. I have just added a new test.com domain and three SOA, NS, and A records and able to dig those records.

```
$ dig +short @192.168.122.128 test.com SOA
ns1.test.com. hostmaster.test.com. 2019010101 21600 3600 1209600 300

$ dig +short @192.168.122.128 test.com NS
ns1.test.com.

$ dig +short @192.168.122.128 ns1.test.com A
192.168.122.128
```

Try to create an exact copy of the existing example.com records, but for your domain name.

**Comment by chenglonglinux** [comment]
i have same issues too,
new centos follow the step, add new domain and A record, 
Not able lookup too
if you want i can provide the server login too.

**Comment by chenglonglinux** [comment]
if you  want i can provide the server login too.

**Comment by chenglonglinux** [comment]
> Hi,
> 
> Any update on this ?

i know what issues now,
you need add soa record first.

**Comment by binsil** [comment]
Hi,

Thank you for the clarification. I have added the SOA record first for the domain to get the proper result. Now, I need to test the load balancing and DNS failover. I have added two domains which point to two servers with wp installation. I have tried adding the following status checks mentioned in the screenshot. However, I am getting the status OFF for the domains on the status check bar and the dig report only show SOA after adding the status checks. Can you check and advise me on this.

2. Also, I have tried adding the following HTTP parameters to create a new status check, however the results are same.
`````
{"type": "http", "url": "https://domain_name.com/index.php", "interval": 3, "timeout": 1, "fall": 3, "rise": 5}
`````
![power_status](https://user-images.githubusercontent.com/53219891/63030616-3b5df880-bed0-11e9-8304-b312e02df8bc.png)
