### ISSUE TITLE
how  to  enabled   master   slave syn ?

### ISSUE THREAD

**Issue by w796933** [AlekseyChudov/powergslb#17]
sir . how  to  enabled powerdns   master   slave syn ?

**Comment by w796933** [comment]
share  remote-connection-string=http:url=http://192.168.0.87:3000/dnsapi  is ok ？

**Comment by acudovs** [comment]
> sir . how to enabled powerdns master slave syn ?

Master-Slave replication https://dev.mysql.com/doc/refman/5.5/en/replication.html
Multi-Master replication http://galeracluster.com/

> share remote-connection-string=http:url=http://192.168.0.87:3000/dnsapi is ok ？

https://github.com/AlekseyChudov/powergslb/blob/master/pdns/pdns.conf#L6

**Comment by w796933** [comment]
is support  DNS Failover & Monitoring checks ?

**Comment by acudovs** [comment]
> is support DNS Failover & Monitoring checks ?

https://github.com/AlekseyChudov/powergslb/blob/master/README.md#health-checks

**Comment by w796933** [comment]
i have  2 web server .
how to setup    Normal situation points to primary IP, if primary IP fails, auto switch to standby iP  ？

**Comment by acudovs** [comment]
Set up a health check for A records and increase the weight of the primary record OR set fallback for standby records (in fact, the result will be the same for only two records).

**Comment by w796933** [comment]
Don't understand, can you give me a demonstration?  so  thanks .

**Comment by acudovs** [comment]
Primary (fallback 0)

![Screenshot from 2020-01-09 12-06-04](https://user-images.githubusercontent.com/3115312/72058532-eb495d80-32d8-11ea-8134-076be20362c2.png)

Standby (fallback 1)

![Screenshot from 2020-01-09 12-07-03](https://user-images.githubusercontent.com/3115312/72058543-f00e1180-32d8-11ea-95ab-5d83ce08f675.png)

**Comment by w796933** [comment]
okay . so thanks . 
 if   one Primary   two Standby  fallback is   0  1  2 ?

**Comment by acudovs** [comment]
It depends on your needs. If both standby servers have the same weight, both will be returned by DNS in case of a failure of the primary server. If the standby servers have different weights, they will be returned by DNS in order of their weight.

**Comment by w796933** [comment]
Primary  set  fallback  is 0   . standby servers set  fallback is 1 . but  dns responds to 2 records at the same time. I just want the master server to return to the master server iP in the normal state. The main machine is down. Returning the backup IP automatically

**Comment by acudovs** [comment]
I'm sorry for incorrect answer. Please try "weight" instead of "fallback".

**Comment by w796933** [comment]
okay. i  setup   weight .  if  two server  is down . how to setup  default   records .

**Comment by acudovs** [comment]
And what do you want to return if both servers are down?

**Comment by w796933** [comment]
if  both  server  are down .i want  to return  default   records .

**Comment by acudovs** [comment]
You can configure the records as shown in the table

Name | Type | Content | Weight | Monitor
-|-|-|-|-
test.example.com | A | 1.1.1.1 | 100 | HTTP request /status
test.example.com | A | 2.2.2.2 | 10 | HTTP request /status
test.example.com | A | 3.3.3.3 | 1 | No check

**Comment by w796933** [comment]
i  two  powerdns server   setup Multi-Master replication  .  so   health check  from  two server  ?

**Comment by acudovs** [comment]
The health checks are independent for PowerGSLB instances. So yes, health checks are performed from two servers in the case of two nodes.

**Comment by w796933** [comment]
/usr/sbin/powergslb -c /etc/powergslb/powergslb.conf


DEBUG: Monitor: Monitor thread started
INFO: Monitor: MonitorThread: update checks from the database
DEBUG: Monitor: Monitor thread stopped
Exception in thread Monitor:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/powergslb/system/thread.py", line 26, in run
    self.task()
  File "/usr/lib/python2.7/site-packages/powergslb/monitor/monitor.py", line 179, in task
    self._update_checks()
  File "/usr/lib/python2.7/site-packages/powergslb/monitor/monitor.py", line 100, in _update_checks
    with powergslb.database.Database(**powergslb.system.get_config().items('database')) as database:
  File "/usr/lib/python2.7/site-packages/mysql/connector/connection.py", line 118, in __init__
    self.connect(**kwargs)
  File "/usr/lib/python2.7/site-packages/mysql/connector/connection.py", line 377, in connect
    self.config(**kwargs)
  File "/usr/lib/python2.7/site-packages/mysql/connector/connection.py", line 276, in config
    self.set_login(user, password)
  File "/usr/lib/python2.7/site-packages/mysql/connector/connection.py", line 926, in set_login
    self._password = password.strip()
AttributeError: 'int' object has no attribute 'strip'


mysql -upowergslb -p123456  -h127.0.0.1  powergslb

i sure  mysql  can .   connect .

**Comment by acudovs** [comment]
Do not use passwords containing only numbers!
