### ISSUE TITLE
is it possible to use in debian or ubuntu

### ISSUE THREAD

**Issue by catding** [AlekseyChudov/powergslb#18]
Hi Aleksey
your DNS system is amazing, I have a small box of Debian with 512M RAM, is it possible to build from the source and use it?

thanks.

**Comment by acudovs** [comment]
Although it is possible to compile deb packages from python setuptools or install PowerGSLB from source, there is no step-by-step guide for this. Any contribution is welcome.

So, for Debian based distributions, I recommend using the PowerGSLB Docker image:
1. https://docs.docker.com/install/linux/docker-ce/debian/
2. https://github.com/AlekseyChudov/powergslb#using-powergslb-docker-image

I just tested it on the latest Debian 9, but Debian 10 should also work.
