### ISSUE TITLE
not possible to delete a domain

### ISSUE THREAD

**Issue by cronzr** [AlekseyChudov/powergslb#2]
Hi Alexey.
  Thanks a lot for your project. I'm just trying to use your program. Currently it's not possible to delete a domain due to constraint in database. there are no records at all. 

error message is :

1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`powergslb`.`names`, CONSTRAINT `names_domains_id_fk` FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`))

Thanks!

**Comment by AlekseyChudov** [comment]
Hi,

Just tried to create new domain test.com, add some records to test.com domain, delete these records and delete domain without problems.

Are there any records for domain you are trying to delete? You must delete them first.
Can you report steps to reproduce the problem? Please make sure you are using latest powergslb version 1.6.3.

Aleksey

**Comment by acudovs** [comment]
Please try latest version 1.6.4
