### ISSUE TITLE
Cannot build docker image

### ISSUE THREAD

**Issue by Outstep** [AlekseyChudov/powergslb#3]
Hello,

I tried to build your powerslbl to create a docker container, but it failed.

I have a MySQL cluster setup and would like to run your docker-pdns to connect to it as well.

Is there a docker image available on Docker Hub (https://hub.docker.com/)

Maybe I can pull it from there?

Thanks,
Lonnie

**Comment by Outstep** [comment]
Hello,

I was able to get it all to build, and then I started it up 

VERSION=1.6.4
docker run -d --name powergslb --hostname powergslb powergslb:"$VERSION"

but when I try to connect to:

https://localhost/admin

it does not connect.

Is there a way for me to specify  for powergslb to build and use an external MySQL/MariaDB cluster that I have setup and running?

Cheers,
Lonnie

**Comment by acudovs** [comment]
Hi Lonnie,

localhost is your computer address, not container. Please execute the following command to show the running container address
`docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' powergslb`

Execute the following command to enter running container and change database address in /etc/powergslb/powergslb.conf configuration file
`docker exec -it powergslb bash`

PS. All of the mentioned commands are in the README.md file.

Aleksey

**Comment by Outstep** [comment]
Hi Aleksey,

Thanks for getting back to me on this. I have actually already gone through the listed commands in the READ.me that you have provided as I wanted to just do a step-by-step build and run it in docker just as you have presented as a first step before doing an external connection to another database..  


I was able to build it and run it, but then could bring up the web interface on the localhost for some reason which is the current hold up point.

Cheers,
Lonnie

**Comment by Outstep** [comment]
Hi Aleksey,

I just did a fresh build from scratch:

Step 1) 
VERSION=1.6.4

Step 2) 
docker build -f docker/Dockerfile --build-arg VERSION="$VERSION" \
    --force-rm --no-cache -t powergslb:"$VERSION" https://github.com/AlekseyChudov/powergslb.git

[powergslb-build-msg.txt](https://github.com/AlekseyChudov/powergslb/files/1099879/powergslb-build-msg.txt)

Step 3)
root@spartan:~# docker run -d --name powergslb --hostname powergslb powergslb:"$VERSION"

b8cf711563fbf85a76f8b954b580a046f501e425745b8136ea5f53f36bd8987b

Step 4)
root@spartan:~# docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' powergslb

172.17.0.2

Then I opened up a chrome browser to:

https://localhost/admin

and I get
-----------------------------------
This site can’t be reached

localhost refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
-----------------------------------

I have attached a build log from Step 1 through the build and did see a couple of errors, but not sure if they are relevant or not.

Thanks,
Lonnie

**Comment by acudovs** [comment]
You should open container address (from step 4) https://172.17.0.2/admin, not localhost.

**Comment by Outstep** [comment]
I actually forgot to mention, but I actually did try that as well:

https://172.17.0.2/admin

-------------------------------------------
This site can’t be reached

172.17.0.2 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
--------------------------------------------

I'm just using Ubuntu 16.04 and everything seems to work with other docker apps that I try so I have to conclude that either something is mis-configured or perhaps I built something incorrectly.

Thanks again for looking into this for me.
Lonnie

**Comment by Outstep** [comment]
Just a thought, but I do have 2 images created during the build process.

root@spartan:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
powergslb           1.6.4               d7bf7c1b6d6d        2 hours ago         562.7 MB
centos              7.3.1611            67591570dd29        6 months ago        191.8 MB

Do I need to also start up the "centos" container as well since I do not see anywhere that we are exposing any ports from the "powergslb" container with a port switch when running the powergslb container. Maybe I missed something here?

Cheers,
Lonnie

**Comment by Outstep** [comment]
I still have not been able to get your PowerDNS docker version to work and I do not know if you have been able to replicate the problem that I am having with the basic connection to the Power Admin but it seems that either something is not working in the build or I am doing something incorrectly.

In either case, I cannot get a working version.

Can you please do a complete build based upon your site information to see if it works for you and let me know as I really would like to try and use your version, but if it is not going to work for me then I may have to try another option.

Alternatively, could you possibly place a build on Docker Hub that can just be pulled and made to work with an external MySQL server which is really what I need?

Thanks again for all of your help and assistance in trying to get this to work.

Cheers,
Lonnie

**Comment by acudovs** [comment]
Hi,

Sorry for delay. No spare time last week. I will look on it this week.

Aleksey

**Comment by Outstep** [comment]
Great, I'll look forward to seeing if you can get it all working without the problems that I encountered.

Cheers,
Lonnie

**Comment by Outstep** [comment]
Greetings Aleksey,

Did you have any luck with installing everything and connecting to an external MySQL server?

I would still like to use your docker container setup for my PowerDNS and Web interface, if at all possible.

Cheers,
Lonnie

**Comment by acudovs** [comment]
You can pull powrgslb image from docker.io if it still makes sense

docker pull docker.io/alekseychudov/powergslb:1.6.4
docker run -d --name powergslb --hostname powergslb docker.io/alekseychudov/powergslb:1.6.4

But it runs on CentOS host only because of systemd inside container.

**Comment by acudovs** [comment]
If you want to connect to external MySQL server, you should edit powergslb.conf and commit new image.
