### ISSUE TITLE
balance weight record

### ISSUE THREAD

**Issue by felipegabriel** [AlekseyChudov/powergslb#6]
In Route53 there is balancing, here always return 192.0.2.104.

Is it possible to balance in 192.0.2.104 and 192.0.2.103?
192.0.2.104 size is 2, 192.0.2.103 is 1. Should get out more 192.0.2.104 instead 192.0.2.103

![powergslb](https://user-images.githubusercontent.com/3071322/43038602-adee1562-8cf2-11e8-983e-df09a43618fb.jpg)

**Comment by acudovs** [comment]
Please try this fork https://github.com/aromeyer/powergslb
