### ISSUE TITLE
Multi tenant

### ISSUE THREAD

**Issue by portalizer** [AlekseyChudov/powergslb#8]
can i use multi-tenancy in powergslb?

**Comment by acudovs** [comment]
Please explain in more detail what you are trying to achieve?

**Comment by portalizer** [comment]
i want create another user (not admin user)
like example
1 user have 1 domain
the user only can modified record on that domain and cant see another domain or record

thats my goal
Thanks

**Comment by acudovs** [comment]
Unfortunately current version of PowerGSLB does not support multiple tenants. All created users have administrator rights.

**Comment by portalizer** [comment]
ok thanks aleksey
i hope it will be available in next version

**Comment by acudovs** [comment]
It takes a lot of refactoring. Some role-based access control should be implemented. The user interface is the easiest part. All read and write operations must verify the user's role before proceeding. I will try to implement it in my free time.
