### ISSUE TITLE
Paid support of the software

### ISSUE THREAD

**Issue by iprok** [AlekseyChudov/powergslb#9]
Hello, Alexsey!
We are going to install powergslb in our infrastructure. We need to make some fixes in it and also we are interested in paid support of it. Can we discuss it with you? If so please send me email to iprok at kinetiksoft dot com .

With best regards, Ivan.

**Comment by acudovs** [comment]
Hi Ivan,

PowerGSLB is an educational project. It is not optimized for performance, security or multiple tenants. Of course, you can use it in the production infrastructure, but without any guarantees. If you find any errors or want to implement some additional features, please write them here and I will answer whether it is possible to implement them without a huge refactoring. As for paid support, I do not have enough free time to provide a decent level of service.

Aleksey

**Comment by iprok** [comment]
Thank you. It's very good for educational project.
